[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cloudevents-python>=0.2.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.0.0",
    "redis>=7.1.1",
    "rq>=2.6.1",
    "rq-scheduler>=0.14.0",
]
